# Отключить проблемные линтеры
DISABLE_LINTERS:
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - PYTHON_FLAKE8
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - SPELL_CSPELL
  - PYTHON_MYPY

# Автофиксы
APPLY_FIXES: all

# Сделать некритичными
PYTHON_ISORT_DISABLE_ERRORS: true
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
YAML_PRETTIER_DISABLE_ERRORS: true
COPYPASTE_JSCPD_DISABLE_ERRORS_IF_LESS_THAN: 5

COPYPASTE_JSCPD_ARGUMENTS: "--gitignore --threshold 5"

# Отчеты
FILEIO_REPORTER: false
GITHUB_STATUS_REPORTER: false

# mypy
PYTHON_MYPY_FILTER_REGEX_INCLUDE: "app/.*"
PYTHON_MYPY_FILTER_REGEX_EXCLUDE: ""
