services:
  bot:
    build: .
    container_name: telegram_bot
    volumes:
      - .:/src
    restart: always
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    cap_drop:
      - ALL
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f https://api.telegram.org/bot${tg_bot_token}/getMe || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
