name: MegaLinter

on: [push, pull_request]

jobs:
  megalinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v8.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
